name: salesforce
description: Absensi Sales dan Sales Order Maker

publish_to: 'none'

version: 0.0.1+6

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  vibration: ^2.0.0
  qr_code_scanner_plus: ^2.0.12
  font_awesome_flutter: ^10.7.0
  audioplayers: ^6.1.0
  intl: ^0.20.2
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  card_swiper: ^3.0.1
  skeletonizer: ^2.1.0+1
  expansion_tile_group: ^2.1.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  http: ^1.2.2
  flutter_localization: ^0.3.3
  share_plus: ^10.1.0
  cached_network_image: ^3.4.1
  package_info_plus: ^8.1.0
  marquee: ^2.3.0  
  toastification: ^2.3.0
  slide_digital_clock_fork: ^1.0.4
  camera: ^0.11.0+2
  image: ^4.1.3
  flutter_image_compress: ^2.4.0 
  geolocator: ^13.0.2
  geocoding: ^2.1.1    
  dotted_border: ^3.1.0
  quickalert: ^1.1.0
  flutter_launcher_icons: ^0.14.4
  syncfusion_flutter_datepicker: ^31.2.2
  url_launcher: ^6.3.2
  upgrader: ^12.3.0
  flutter_device_imei: ^0.0.4
  
  # flutter_localizations: any
  # path: any
dev_dependencies:
  flutter_test:
    sdk: flutter

    



flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/categories_images/
    - assets/images/grocery_images/
    - assets/images/beverages_images/
    - assets/images/payments/
    - assets/icons/
    - assets/icons/account_icons/
    - assets/fonts/
    - assets/audio/    
    - assets/svg/    

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"